import "./styles/reset.css";
// import "./styles/style.scss";
import { Inter } from 'next/font/google'
import { Header } from "./components/Header";
import MobileMenu from "./components/MobileMenu";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        <MobileMenu />
        {children}
      </body>
    </html>
  )
}